### ISSUE TITLE
ERC20 program in Rust

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#1]
Write a program to manage ERC20 tokens in Rust, which can be proved with Risc0, and deploy it on Hylé.
Here's the documentation to code [your 1st smart contract on Hylé](https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/).

Here's an [example of the Cairo ERC20 contract](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token) used for the [vibe check demo](https://vibe.hyle.eu/).

**Comment by Immanuelolivia1** [comment]
Hi @s0lness I can work on this issue

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hey @fricoben, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

### How I plan on tackling this issue
I would implement every requirement of an ERC20 token in Rust contract

**Comment by g4titanx** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
have got experience contributing to projects like the nearsdk, dojo, etc

### How I plan on tackling this issue
thru the provided method and my own knowledg initiative

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.


### How I plan on tackling this issue
I will work on this issue by following these steps:

1. Implement the ERC20 Contract in Rust
I will start by writing the ERC20 token contract in Rust, adhering to the ERC20 standard.
The contract will include all necessary functions such as transfer, approve, transferFrom, and balanceOf.
I will ensure that the contract is compatible with Risc0, allowing it to generate verifiable proofs for state transitions.
2. Integrate Risc0 for Proof Generation
I will integrate Risc0 into the Rust codebase to enable proof generation for the state transitions within the ERC20 contract.
This will involve creating proofs for operations like token transfers and ensuring these can be verified on-chain using the Hylé platform.
3. Deploy the Contract on Hylé
Following the deployment guidelines provided in the Hylé documentation, I will deploy the Rust-based ERC20 contract on the Hylé devnet.
This will include registering the contract on-chain, verifying that it functions as expected, and interacting with it through stateful transactions.
4. Documentation and Example Integration
I’ll document the entire process, including how to compile the Rust contract, generate Risc0 proofs, and deploy the contract on Hylé.
I will also update the README to include detailed instructions and examples for users to interact with the deployed contract.
5. Testing and Validation
After deployment, I’ll rigorously test the contract to ensure it operates correctly on Hylé.
I’ll verify that the Risc0 proofs are generated accurately and that state transitions are reflected on-chain as expected.

**Comment by the-first-elder** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm a fullstack blockchain dev

### How I plan on tackling this issue
i Would  program to manage ERC20 tokens in Rust, and deploy it on Hylé usings the docs as a guide

**Comment by chachaleo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I have a degree in applied mathematics engineering and have worked as a ZKML Engineer

### How I plan on tackling this issue
Read the example and the `your 1st smart contract on Hylé`

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a full stack web3 developer with experience in developing dapps. I have also contributed to core ETH repos on Golang and Rust clients.

### How I plan on tackling this issue
I have written Rust smart contracts before and I will utilize that knowledge to write the smart contract for ERC20 tokens in rust. I will ensure that my code is:
1. efficient
2. well documented
3. comments added for difficult sections
4. error free

Here are the functions for the ERC20 contract:
```
total_supply
balance_of
transfer
approve
transfer_from
allowance
mint
burn
ownership
transfer_ownership
pause
unpause
snapshot
event_emission
```

**Comment by wraitii** [comment]
Hello all, thanks for applying 😄 

Assigning this one to @chachaleo.
For this one, the best starting point is http://github.com/Hyle-org/collatz-conjecture since that's Rust + risc0. Consider looking at our vibe checks contracts as well.

For questions, please join [t.me/hyle_org](https://t.co/irOrk82eHL). We try to keep the docs at https://docs.hyle.eu up-to-date but things change quickly.
