### ISSUE TITLE
Proof of membership

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#13]
Write a program in any provable language (Cairo, Noir, Circom, Rust) to verify a user is part of a group.

**Comment by od-hunter** [comment]
Hi @s0lness , can I be assigned this? This would be my first time contributing to this ecosystem.

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo

### How I plan on tackling this issue
To address this problem in Cairo, start by defining the group as an array or set of user identifiers or addresses. Implement a function that takes a user’s address as input and checks if it exists in the group. If the address is found, return a value indicating the user is part of the group; otherwise, return a value indicating they are not. Finally, test the program with various inputs to ensure it works correctly.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a blockchain developer with vast experience. Please give me the opportunity to contribute. 

### How I plan on tackling this issue
To solve this issue, I'd use Cairo language and I'd follow these steps:
1. I'll define the data structures by creating a mapping to store user addresses and their membership status.
2. I'll write a function to check and return if a user is part of the group.
3. I'll add functions to add or remove users from the group, updating their membership status accordingly.
4. Lastly, I'll test adding, removing, and verifying user membership to ensure functionality is correct.

Please assign this issue to me I'm ready to work.

**Comment by mahesh-dalle** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I have been exploring zk and rust for a while. I have explored circom circuits and this can be leveraged in this .

### How I plan on tackling this issue
Proof of membership can be implemented using a merkle inclusion proof. This can be used to verify if a user is part of the group.

**Comment by PavitraAgarwal21** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hi, first of all, great project! To introduce myself, I have experience writing Circom circuits, particularly some what related to TornadoCash circuit . I used the nullifier and commitment hash components to verify tickets in a project that won the StarkNet hackathon. Additionally, I utilized their Merkle tree to verify if a person is whitelisted. You can check my GitHub repo for ZKTPS in the circuit section. I also have an in-depth understanding of how proof systems work, although it might not be directly required here.

### How I plan on tackling this issue
To verify that a user is part of a group using Circom, the group is represented as a Merkle tree where each leaf is a hash of a user's identifier, and the root represents the entire group. The user provides a leaf (their hashed identifier), the Merkle Proof (consisting of sibling hashes and their positions along the path to the root), and the known root. The circuit recomputes the root by traversing from the leaf using the Merkle Proof and checks if the recomputed root matches the provided root. If they match, the user is verified as part of the group. This approach ensures membership verification without revealing other members' identities.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community.

### How I plan on tackling this issue
1. Designing the Proof of Membership
The goal is to create a ZKP where a user can prove their membership in a group (e.g., a Merkle tree or another set structure) without revealing their identity or the full group.
I’ll design the proof logic to take the group’s commitment (such as a Merkle root) and the user’s corresponding proof (like a Merkle path) as inputs.
2. Implementing the Cairo Program
I will write the Cairo code that constructs the proof of membership.
This will involve:
Constructing the Proof: Writing Cairo functions that take in the group commitment and the user’s membership proof to verify the user’s membership.
Handling Inputs and Outputs: Ensuring that the Cairo program correctly handles the inputs (e.g., group commitment, user proof) and produces the correct proof outputs.
3. Testing and Verification
I will create a series of test cases to ensure the correctness of the proof. This will include:
Valid Membership Tests: Verifying that valid members pass the proof.
Invalid Membership Tests: Ensuring that non-members or invalid proofs fail the verification.
I’ll also test the Cairo program’s performance and efficiency, making optimizations as needed.
4. Documentation and Integration
Once the proof of membership is implemented and tested, I’ll document the code thoroughly to ensure it’s understandable and maintainable.
I’ll also explore how this proof can be integrated into broader systems or protocols that require membership verification.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I have experience with Cairo and blockchain development, which involves writing and verifying smart contracts. I can leverage this expertise to develop a verification program that ensures a user is part of a group using Cairo’s zero-knowledge proof capabilities. This would involve defining the group membership criteria in a verifiable way and implementing the logic in Cairo to validate the user’s membership.

### How I plan on tackling this issue
I would start by defining the group membership criteria and encoding this logic into the chosen language. For example, in Cairo, I’d write a smart contract that includes the necessary group verification logic and uses zero-knowledge proofs to ensure the user’s membership can be validated without revealing additional information. I’d then test the program thoroughly to ensure accuracy and reliability.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am front end developer with years of experience.
this will be my first time contributing to the ecosystem and i am ready to work

### How I plan on tackling this issue
// Define the group members
%{ 
    group_members = [0x123, 0x456, 0x789]
%}

// Function to verify if a user is part of the group
func is_member_of_group(user_address: felt) -> (is_member: felt):
    alloc_locals
    local i: felt = 0
    loop:
        if i >= len(group_members):
            return (is_member=0)
        end
        if group_members[i] == user_address:
            return (is_member=1)
        end
        i += 1
        jmp loop
    end
end

cairo

Copy
// Check if the user with address 0x123 is a member of the group
let (is_member) = is_member_of_group(0x123);
assert is_member == 1;

// Check if the user with address 0xabc is a member of the group
let (is_member) = is_member_of_group(0xabc);
assert is_member == 0;

**Comment by wraitii** [comment]
Hello all, thanks for applying 😄 

Assigning this one to @PavitraAgarwal21 
We don't support raw Circom yet, but you might be able to use Gnark regardless (not entirely sure). Alternatively, you can go for Rust or Cairo.
We have Risc0 in [Collatz](http://github.com/Hyle-org/collatz-conjecture) and Cairo in [Vibe Check](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token). We have Gnark examples in the Hylé repo directly.

For questions, please join [t.me/hyle_org](https://t.co/irOrk82eHL). We try to keep the docs at https://docs.hyle.eu up-to-date but things change quickly.
