### ISSUE TITLE
ERC20 program in Noir

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#2]
Write a program to manage ERC20 tokens in Noir and deploy it on Hylé.
Here's the documentation to code [your 1st smart contract on Hylé](https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/).

Here's an [example of the Cairo ERC20 contract](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token) used for the [vibe check demo](https://vibe.hyle.eu/).
Here's the [example of the Noir program](https://github.com/Hyle-org/vibe-check/tree/main/noir-webauthn) used to verify ECDSA signatures.

**Comment by 0xmihirsahu** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I have a solid background in blockchain development, with extensive experience in creating and managing smart contracts, especially on Ethereum. I’m skilled in Solidity and learning Cairo. I just started reading about Zero-Knowledge proof from the moon math manual.

### How I plan on tackling this issue
I’d begin by understanding and reading a few things before diving straight into coding. Then, I’d design and develop the smart contract using Noir, incorporating Zero Knowledge Proofs (ZKPs) for added security.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hello, I'll like to be assigned to work on this. I am a first time contributor and would love to be given the opportunity. I have worked on a similar project like this

**Comment by the-first-elder** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hi, I'm a fullstack web3 dev

### How I plan on tackling this issue
I Would  write an ERC20 tokens in Noir, and deploy it on Hylé usings the docs as a guide

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am an experienced Rust and Cairo programmer. I have also contributed to many blockchain repos involving smart contracts in Cairo and Rust. Learning to write and deploy contracts in Noir will be fun.

### How I plan on tackling this issue
Follow the given examples of Cairo ERC20 contract and Noir program to verify ECDSA signatures to write the Noir contract for ERC20 from scratch. After successfully writing the smart contract, I will make sure to:
1. Write a proper readme file for the package so that new contributors can setup easily and understand the code
2. Ensure a clean, readable and error-free codebase
3. Proper parsing and efficient function to avoid overcomplicating the code
4. Adding comments to the difficult parts of code when and wherever required.
5. Test the contract on Hyle network and check all functions to be working as expected before PR

**Comment by Psalmuel01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a Web3 frontend developer with 2 years of experience, specializing in creating seamless user experiences and integrating blockchain technologies. My background in smart contract development and blockchain integration, combined with my experience in deploying contracts on various platforms, positions me well to tackle this task. I have worked extensively with different blockchain frameworks and am familiar with the nuances of ERC standards, particularly ERC721. My ability to quickly adapt to new environments, like Noir and Hylé, allows me to leverage my existing knowledge while effectively learning and implementing new technologies.

I'm new to OnlyDust, and would be happy if this becomes my first assigned issue. Thank you.

### How I plan on tackling this issue
How I Would Approach the Problem:

1. Understand the Noir Language and Hylé Platform:
Review the provided documentation for writing smart contracts in Noir and familiarize myself with Hylé’s deployment process. This step ensures that I fully grasp the syntax, capabilities, and constraints of the Noir language and the specific requirements for deploying on Hylé.

2. Design the ERC20 Token Contract:
Design the smart contract structure, focusing on key functionalities such as minting, transferring, and burning tokens. I would also implement necessary functions like balanceOf, ownerOf, and approve, adhering to the ERC20 standard.

3. Implement the Contract in Noir:
Write the ERC20 contract in Noir, ensuring that the code is efficient and follows best practices. I would include comments and documentation within the code for clarity and maintainability.

4. Deploy on Hylé:
Once the contract passes all tests, I would deploy it on the Hylé platform. This step involves configuring the deployment settings according to Hylé’s requirements and monitoring the deployment process to ensure it completes successfully.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
i'm a frontend dev and a blockchain developer, will love to take on this issue and get it done if you give me the chance

### How I plan on tackling this issue
Understand ERC20 Tokens

Learn the ERC20 standard functions and requirements.
Learn Noir

Get familiar with Noir programming language and its syntax.
Review Hylé Documentation

Study how to deploy smart contracts on Hylé.
Examine Examples

Review the Cairo ERC20 contract example and Noir ECDSA signature example for guidance.
Write the ERC20 Contract in Noir

Define the contract structure and implement ERC20 functions (e.g., transfer, approve).
Test the Contract Locally

Verify the contract’s functionality through local testing.
Deploy on Hylé

Use Hylé’s tools to deploy your Noir ERC20 contract.
Verify and Interact

Ensure the contract operates correctly and interact with it to confirm its functionality.

**Comment by abhilov23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hii, Abhilov This side. I am currently working as a blockchain developer. I would like to resolve this issue and want to take a deep dive into Hylé Ecosystem through open-source.
