### ISSUE TITLE
ERC721 program in Noir

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#5]
Write a program to manage ERC721 tokens in Noir, and deploy it on Hylé.
Here's the documentation to code [your 1st smart contract on Hylé](https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/).

Here's an [example of the Cairo ERC20 contract](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token) used for the [vibe check demo](https://vibe.hyle.eu/).

**Comment by BenFaruna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hello, I am a software engineer with over 4 years of experience. I have experience working with several programming languages including solidity, cairo. I believe my understanding of smart contract development and the ERC721 contract can help me tackle this issue.

### How I plan on tackling this issue
I would be using the standard of EIP 721 while i write the contract to implement the functionalities of the contract. After writing each functionality, I would be testing by deploying on a local testnet to ensure it works as expected. This would be my first time writing noir and I am open to feedback and constructive criticisms. The language shares similarities with cairo and I am willing to use that knowledge to speed up the development process.

**Comment by kfastov** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a software developer with 4 years of blockchain experience. I already wrote several smart contracts with ERC721 and ERC1155 interface in Cairo, and now as I learn Noir, I want to practice it writing this smart contract.

### How I plan on tackling this issue
I would take a reference ERC721 implementation in Cairo and Solidity (e.g. by OpenZeppelin) and gradually implement it in Noir, considering all possible edge cases. Then I'll learn how the contracts are deployed on Hylé and deploy the new contract there

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hello @s0lness I'm Diego Duarte Fernández from Costa Rica and Dojo Coding member this is my OnlyDust profile: https://app.onlydust.com/u/diegoTech14, I would love to help with this issue. 

I have some experience creating Smart Contracts in Cairo and I understand the ERC721, I would love to take this opportunity to contribute to Hylé and explore Noir, I would like to get feedback if this issue is assigned to me.

### How I plan on tackling this issue
1. Inspiring in Cairo ERC721 reference: First of all I will take as an example the Cairo ERC721 reference to gradually implement it in Noir.

2. Implementing: I will implement the ERC721 in Noir following the best code practices and the Noir documentation

3. Testing: I will test the contract on a local testnet to ensure that everything is okay

If it is needed I could update the readme to explain the installation and how to run/test the smart contract.

Thanks for the consideration.

Best regards, 

Diego Duarte Fernández

**Comment by the-first-elder** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm a fulls-tack blockchain dev

### How I plan on tackling this issue
i Would read the hyle docs to familiarize myself with the syntax and recreate erc721

**Comment by JuanPabloRodriguezC** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a computer engineer student with a lot of experience on low and high level languages. I have been learning cairo and rust in the last few months, I am already familiar with all the documentation, I completed most of starklings exercises. This would be my first smart contract and I would love to give it a go!

### How I plan on tackling this issue
-Install CLI tools
-Write smart contract using RISC Zero Collatz conjecture and following Cairo documentation
-Deploy on Hylé

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am an experienced Rust and Cairo programmer. I have also contributed to many blockchain repos involving smart contracts in Cairo and Rust. Learning to write and deploy contracts in Noir will be fun.

### How I plan on tackling this issue
Follow the given example of Cairo ERC20 contract to write the Noir contract for ERC721 from scratch. After successfully writing the smart contract, I will make sure to:
1. Write a proper readme file for the package so that new contributors can setup easily and understand the code
2. Ensure a clean, readable and error-free codebase
3. Proper parsing and efficient function to avoid overcomplicating the code
4. Adding comments to the difficult parts of code when and wherever required.
5. Test the contract on Hyle network and check all functions to be working as expected before PR

**Comment by Psalmuel01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a Web3 frontend developer with 2 years of experience, specializing in creating seamless user experiences and integrating blockchain technologies. My background in smart contract development and blockchain integration, combined with my experience in deploying contracts on various platforms, positions me well to tackle this task. I have worked extensively with different blockchain frameworks and am familiar with the nuances of ERC standards, particularly ERC721. My ability to quickly adapt to new environments, like Noir and Hylé, allows me to leverage my existing knowledge while effectively learning and implementing new technologies.

I'm new to OnlyDust, and would be happy if this becomes my first assigned issue. Thank you.

### How I plan on tackling this issue
How I Would Approach the Problem:

1. Understand the Noir Language and Hylé Platform:
Review the provided documentation for writing smart contracts in Noir and familiarize myself with Hylé’s deployment process. This step ensures that I fully grasp the syntax, capabilities, and constraints of the Noir language and the specific requirements for deploying on Hylé.

2. Design the ERC721 Token Contract:
Design the smart contract structure, focusing on key functionalities such as minting, transferring, and burning tokens. I would also implement necessary functions like balanceOf, ownerOf, and approve, adhering to the ERC721 standard.

3. Implement the Contract in Noir:
Write the ERC721 contract in Noir, ensuring that the code is efficient and follows best practices. I would include comments and documentation within the code for clarity and maintainability.

4. Deploy on Hylé:
Once the contract passes all tests, I would deploy it on the Hylé platform. This step involves configuring the deployment settings according to Hylé’s requirements and monitoring the deployment process to ensure it completes successfully.

**Comment by MachoMaheen** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I have a solid foundation in blockchain development, with specific expertise in creating and deploying smart contracts using various languages and platforms. My experience includes working with Solidity, Cairo, and Noir for developing decentralized applications and handling token standards like ERC20 and ERC721. My previous projects, such as the development of Certify-ETH at ETHIndia 2022 and participation in StarkNet hackathons, involved working with smart contracts for secure and efficient digital asset management.

I am also proficient in Rust, a language that shares similarities with Noir, which will aid in understanding and implementing Noir smart contracts. My experience in deploying smart contracts on different blockchains, including StarkNet and Shardeum, equips me with the knowledge to adapt to new platforms like Hylé efficiently. I’ve worked on integrating smart contracts with various front-end frameworks and have a strong understanding of the underlying principles of token standards and blockchain interactions.


### How I plan on tackling this issue
To approach the problem of writing an ERC721 program in Noir and deploying it on Hylé, I would take the following steps:

1. **Understand the Noir Language and Hylé Platform**:
   - I would start by thoroughly reviewing the Noir documentation and understanding its syntax, semantics, and unique features compared to other smart contract languages I’ve used. This would include understanding how Noir handles token management and contract interactions.
   - Similarly, I would familiarize myself with the Hylé platform, understanding its deployment process, and how it interfaces with Noir smart contracts.

2. **Review ERC721 Token Standard**:
   - I would revisit the ERC721 token standard to ensure I am clear on its requirements, such as implementing the functions `balanceOf`, `ownerOf`, `transferFrom`, `approve`, `setApprovalForAll`, and `safeTransferFrom`. Understanding these functions’ purpose and how they manage ownership and transfer of NFTs is crucial.
   - I would also analyze the Cairo ERC20 contract provided for the vibe check demo to identify any relevant design patterns or techniques that could be adapted to the ERC721 implementation in Noir.

3. **Design the ERC721 Smart Contract in Noir**:
   - I would start by defining the core structure of the ERC721 contract, including state variables to track ownership, balances, and approved addresses.
   - Implementing the essential functions, I would focus on ensuring that each function adheres to the ERC721 standard while leveraging Noir’s features for security and efficiency.
   - I would include safety checks and events to emit relevant transaction information, providing transparency and traceability of token transfers.

4. **Testing and Debugging**:
   - Once the contract is written, I would conduct rigorous testing to ensure its functionality aligns with the ERC721 standard. This would involve writing test cases to simulate various scenarios such as minting, transferring, and burning tokens, as well as edge cases to test contract robustness.
   - I would use Noir’s debugging tools to identify and resolve any issues, ensuring that the contract performs as expected in all situations.

5. **Deploying on Hylé**:
   - After ensuring the contract is functional and secure, I would deploy it on the Hylé platform. This would involve following the specific deployment procedures outlined in Hylé’s documentation, configuring any required parameters, and monitoring the deployment process for any issues.
   - Post-deployment, I would conduct additional tests to ensure that the contract interacts correctly with the Hylé environment and that all functionalities, including token transfers and ownership management, work seamlessly on the platform.

6. **Documentation and Optimization**:
   - I would document the entire process, explaining the design choices, implementation details, and any challenges encountered along the way. This documentation would serve as a reference for future developers working with ERC721 tokens in Noir on Hylé.
   - Finally, I would review the contract for potential optimizations, such as reducing gas costs or improving execution efficiency, ensuring that the smart contract is not only functional but also optimized for real-world usage.

**Comment by DIWAKARKASHYAP** [comment]
https://diwakar-portfolio.vercel.app/  i want to work on this issue

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
i'm a frontend dev and a blockchain developer, will love to take on this issue and get it done if you give me the chance

### How I plan on tackling this issue
Understand ERC721 Tokens:

Familiarize yourself with the ERC721 token standard, which defines how non-fungible tokens (NFTs) work on Ethereum.
Review Noir Documentation:

Study the documentation for coding smart contracts in Noir on Hylé to understand the specific requirements and syntax.
Examine Example Code:

Review the provided Cairo ERC20 contract example for insights into how smart contracts are structured and deployed on Hylé.
Write the ERC721 Contract in Noir:

Develop the ERC721 smart contract using Noir, implementing functions like minting, transferring, and querying token ownership.
Test the Contract:

Write and run tests to ensure your ERC721 contract functions correctly and adheres to the standard.

**Comment by abhilov23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hii, Abhilov This side. I am currently working as a blockchain developer. I would like to resolve this issue and want to take a deep dive into Hylé Ecosystem through open-source.
